### ISSUE TITLE
Anyone working on About Page

### ISSUE THREAD

**Issue by viditvarshney** [technojam/technojam.github.io#7]

**Comment by 20manas** [comment]
Since we are creating another page for events, past events info is not needed.

But apart from this, you can include the rest of the things.

As for the page format, yes, it should have format similar to index.html. It should be exactly the same as index except the stuff written in the article tag inside the body. There you can make the about page.

**Comment by viditvarshney** [comment]
okkk i will do it and look at my anothe PR **#6**
